# Railway config at repository root
[build]
builder = "NIXPACKS"

[build.nixpacks]
# Build the Django backend inside the monorepo
workingDirectory = "backend"

[deploy]
# Start the Django app via Gunicorn
startCommand = "gunicorn sendhisword.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
